// Package internalprobe authenticates HTTP requests generated by trusted
// in-process probes before exposing that trust through request context.
package internalprobe

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"strings"
	"time"
)

const (
	HeaderName          = "X-Sub2API-Internal-Probe"
	signatureVersion    = "v1"
	defaultMaxClockSkew = 60 * time.Second
	maxSignedBodyBytes  = int64(1 << 20)
)

var errProbeBodyTooLarge = errors.New("internal probe request body is too large")

type trustedContextKey struct{}

// Authenticator signs outgoing internal probes and verifies the corresponding
// ingress header. It is immutable after construction and safe for concurrent use.
type Authenticator struct {
	key          []byte
	now          func() time.Time
	random       io.Reader
	maxClockSkew time.Duration
}

// NewAuthenticator derives a purpose-specific HMAC key from the deployment's
// JWT secret. An empty secret disables signing and verification.
func NewAuthenticator(secret string) *Authenticator {
	if strings.TrimSpace(secret) == "" {
		return nil
	}
	sum := sha256.Sum256([]byte("sub2api/internal-probe/v1\x00" + secret))
	return &Authenticator{
		key:          append([]byte(nil), sum[:]...),
		now:          time.Now,
		random:       rand.Reader,
		maxClockSkew: defaultMaxClockSkew,
	}
}

// SignRequest adds a short-lived signature bound to the request method, path,
// query, and body. Callers must separately ensure the target is this deployment.
func (a *Authenticator) SignRequest(req *http.Request) error {
	if a == nil || req == nil {
		return errors.New("internal probe authenticator is disabled")
	}
	body, err := snapshotRequestBody(req)
	if err != nil {
		return err
	}

	timestamp := a.now().UTC().Unix()
	nonce := make([]byte, 16)
	if _, err := io.ReadFull(a.random, nonce); err != nil {
		return fmt.Errorf("generate internal probe nonce: %w", err)
	}
	nonceText := base64.RawURLEncoding.EncodeToString(nonce)
	signature := a.signature(req, body, timestamp, nonceText)
	req.Header.Set(HeaderName, strings.Join([]string{
		signatureVersion,
		strconv.FormatInt(timestamp, 10),
		nonceText,
		base64.RawURLEncoding.EncodeToString(signature),
	}, ":"))
	return nil
}

// VerifyAndMarkRequest always strips the wire-level marker. A valid signature
// is converted to a private context value; invalid markers remain ordinary
// client requests and are never rejected by this verifier.
func (a *Authenticator) VerifyAndMarkRequest(req *http.Request) bool {
	if req == nil {
		return false
	}
	header := strings.TrimSpace(req.Header.Get(HeaderName))
	req.Header.Del(HeaderName)
	if a == nil || header == "" {
		return false
	}

	timestamp, nonce, suppliedSignature, ok := parseHeader(header)
	if !ok || !a.timestampAllowed(timestamp) || !bodyLengthAllowed(req.ContentLength) {
		return false
	}
	body, err := snapshotRequestBody(req)
	if err != nil {
		return false
	}
	expected := a.signature(req, body, timestamp, nonce)
	if !hmac.Equal(suppliedSignature, expected) {
		return false
	}

	ctx := context.WithValue(req.Context(), trustedContextKey{}, true)
	*req = *req.WithContext(ctx)
	return true
}

// IsMarked reports whether a trusted ingress verifier marked this request.
func IsMarked(ctx context.Context) bool {
	if ctx == nil {
		return false
	}
	marked, _ := ctx.Value(trustedContextKey{}).(bool)
	return marked
}

func (a *Authenticator) timestampAllowed(timestamp int64) bool {
	now := a.now().UTC()
	created := time.Unix(timestamp, 0).UTC()
	delta := now.Sub(created)
	if delta < 0 {
		delta = -delta
	}
	return delta <= a.maxClockSkew
}

func (a *Authenticator) signature(req *http.Request, body []byte, timestamp int64, nonce string) []byte {
	bodyHash := sha256.Sum256(body)
	payload := strings.Join([]string{
		signatureVersion,
		strconv.FormatInt(timestamp, 10),
		nonce,
		strings.ToUpper(req.Method),
		canonicalRequestPath(req),
		base64.RawURLEncoding.EncodeToString(bodyHash[:]),
	}, "\n")
	mac := hmac.New(sha256.New, a.key)
	_, _ = mac.Write([]byte(payload))
	return mac.Sum(nil)
}

func parseHeader(header string) (timestamp int64, nonce string, signature []byte, ok bool) {
	parts := strings.Split(header, ":")
	if len(parts) != 4 || parts[0] != signatureVersion {
		return 0, "", nil, false
	}
	timestamp, err := strconv.ParseInt(parts[1], 10, 64)
	if err != nil {
		return 0, "", nil, false
	}
	nonceBytes, err := base64.RawURLEncoding.DecodeString(parts[2])
	if err != nil || len(nonceBytes) != 16 {
		return 0, "", nil, false
	}
	signature, err = base64.RawURLEncoding.DecodeString(parts[3])
	if err != nil || len(signature) != sha256.Size {
		return 0, "", nil, false
	}
	return timestamp, parts[2], signature, true
}

func canonicalRequestPath(req *http.Request) string {
	path := req.URL.EscapedPath()
	if path == "" {
		path = "/"
	}
	if req.URL.ForceQuery || req.URL.RawQuery != "" {
		path += "?" + req.URL.RawQuery
	}
	return path
}

func bodyLengthAllowed(contentLength int64) bool {
	return contentLength >= 0 && contentLength <= maxSignedBodyBytes
}

func snapshotRequestBody(req *http.Request) ([]byte, error) {
	if req.Body == nil || req.Body == http.NoBody {
		return nil, nil
	}
	if !bodyLengthAllowed(req.ContentLength) {
		return nil, errProbeBodyTooLarge
	}
	if req.GetBody != nil {
		copyBody, err := req.GetBody()
		if err != nil {
			return nil, fmt.Errorf("copy internal probe body: %w", err)
		}
		defer func() { _ = copyBody.Close() }()
		body, err := io.ReadAll(io.LimitReader(copyBody, maxSignedBodyBytes+1))
		if err != nil {
			return nil, fmt.Errorf("read internal probe body copy: %w", err)
		}
		if int64(len(body)) > maxSignedBodyBytes {
			return nil, errProbeBodyTooLarge
		}
		return body, nil
	}

	original := req.Body
	body, err := io.ReadAll(io.LimitReader(original, maxSignedBodyBytes+1))
	// Reattach the unread tail as well as the consumed prefix. This keeps an
	// invalid marker observational only, even when the actual stream is larger
	// than its declared Content-Length or reading stops with an error.
	req.Body = &restoredBody{
		reader:   io.MultiReader(bytes.NewReader(body), original),
		original: original,
	}
	if err != nil {
		return nil, fmt.Errorf("read internal probe body: %w", err)
	}
	if int64(len(body)) > maxSignedBodyBytes {
		return nil, errProbeBodyTooLarge
	}
	return body, nil
}

type restoredBody struct {
	reader   io.Reader
	original io.Closer
}

func (b *restoredBody) Read(p []byte) (int, error) {
	return b.reader.Read(p)
}

func (b *restoredBody) Close() error {
	if b.original == nil {
		return nil
	}
	return b.original.Close()
}
