// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/tlsfingerprintrouter"
	"github.com/Wei-Shaw/sub2api/internal/model"
)

// TLSFingerprintRouterCreate is the builder for creating a TLSFingerprintRouter entity.
type TLSFingerprintRouterCreate struct {
	config
	mutation *TLSFingerprintRouterMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TLSFingerprintRouterCreate) SetCreatedAt(v time.Time) *TLSFingerprintRouterCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TLSFingerprintRouterCreate) SetNillableCreatedAt(v *time.Time) *TLSFingerprintRouterCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TLSFingerprintRouterCreate) SetUpdatedAt(v time.Time) *TLSFingerprintRouterCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TLSFingerprintRouterCreate) SetNillableUpdatedAt(v *time.Time) *TLSFingerprintRouterCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *TLSFingerprintRouterCreate) SetName(v string) *TLSFingerprintRouterCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TLSFingerprintRouterCreate) SetDescription(v string) *TLSFingerprintRouterCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TLSFingerprintRouterCreate) SetNillableDescription(v *string) *TLSFingerprintRouterCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *TLSFingerprintRouterCreate) SetEnabled(v bool) *TLSFingerprintRouterCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *TLSFingerprintRouterCreate) SetNillableEnabled(v *bool) *TLSFingerprintRouterCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetRules sets the "rules" field.
func (_c *TLSFingerprintRouterCreate) SetRules(v []model.TLSFingerprintRouterRule) *TLSFingerprintRouterCreate {
	_c.mutation.SetRules(v)
	return _c
}

// Mutation returns the TLSFingerprintRouterMutation object of the builder.
func (_c *TLSFingerprintRouterCreate) Mutation() *TLSFingerprintRouterMutation {
	return _c.mutation
}

// Save creates the TLSFingerprintRouter in the database.
func (_c *TLSFingerprintRouterCreate) Save(ctx context.Context) (*TLSFingerprintRouter, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TLSFingerprintRouterCreate) SaveX(ctx context.Context) *TLSFingerprintRouter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TLSFingerprintRouterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TLSFingerprintRouterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TLSFingerprintRouterCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tlsfingerprintrouter.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := tlsfingerprintrouter.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := tlsfingerprintrouter.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TLSFingerprintRouterCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TLSFingerprintRouter.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TLSFingerprintRouter.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TLSFingerprintRouter.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := tlsfingerprintrouter.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintRouter.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "TLSFingerprintRouter.enabled"`)}
	}
	return nil
}

func (_c *TLSFingerprintRouterCreate) sqlSave(ctx context.Context) (*TLSFingerprintRouter, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TLSFingerprintRouterCreate) createSpec() (*TLSFingerprintRouter, *sqlgraph.CreateSpec) {
	var (
		_node = &TLSFingerprintRouter{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tlsfingerprintrouter.Table, sqlgraph.NewFieldSpec(tlsfingerprintrouter.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Rules(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldRules, field.TypeJSON, value)
		_node.Rules = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TLSFingerprintRouter.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TLSFingerprintRouterUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TLSFingerprintRouterCreate) OnConflict(opts ...sql.ConflictOption) *TLSFingerprintRouterUpsertOne {
	_c.conflict = opts
	return &TLSFingerprintRouterUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TLSFingerprintRouter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TLSFingerprintRouterCreate) OnConflictColumns(columns ...string) *TLSFingerprintRouterUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TLSFingerprintRouterUpsertOne{
		create: _c,
	}
}

type (
	// TLSFingerprintRouterUpsertOne is the builder for "upsert"-ing
	//  one TLSFingerprintRouter node.
	TLSFingerprintRouterUpsertOne struct {
		create *TLSFingerprintRouterCreate
	}

	// TLSFingerprintRouterUpsert is the "OnConflict" setter.
	TLSFingerprintRouterUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TLSFingerprintRouterUpsert) SetUpdatedAt(v time.Time) *TLSFingerprintRouterUpsert {
	u.Set(tlsfingerprintrouter.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TLSFingerprintRouterUpsert) UpdateUpdatedAt() *TLSFingerprintRouterUpsert {
	u.SetExcluded(tlsfingerprintrouter.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *TLSFingerprintRouterUpsert) SetName(v string) *TLSFingerprintRouterUpsert {
	u.Set(tlsfingerprintrouter.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TLSFingerprintRouterUpsert) UpdateName() *TLSFingerprintRouterUpsert {
	u.SetExcluded(tlsfingerprintrouter.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *TLSFingerprintRouterUpsert) SetDescription(v string) *TLSFingerprintRouterUpsert {
	u.Set(tlsfingerprintrouter.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TLSFingerprintRouterUpsert) UpdateDescription() *TLSFingerprintRouterUpsert {
	u.SetExcluded(tlsfingerprintrouter.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *TLSFingerprintRouterUpsert) ClearDescription() *TLSFingerprintRouterUpsert {
	u.SetNull(tlsfingerprintrouter.FieldDescription)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *TLSFingerprintRouterUpsert) SetEnabled(v bool) *TLSFingerprintRouterUpsert {
	u.Set(tlsfingerprintrouter.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *TLSFingerprintRouterUpsert) UpdateEnabled() *TLSFingerprintRouterUpsert {
	u.SetExcluded(tlsfingerprintrouter.FieldEnabled)
	return u
}

// SetRules sets the "rules" field.
func (u *TLSFingerprintRouterUpsert) SetRules(v []model.TLSFingerprintRouterRule) *TLSFingerprintRouterUpsert {
	u.Set(tlsfingerprintrouter.FieldRules, v)
	return u
}

// UpdateRules sets the "rules" field to the value that was provided on create.
func (u *TLSFingerprintRouterUpsert) UpdateRules() *TLSFingerprintRouterUpsert {
	u.SetExcluded(tlsfingerprintrouter.FieldRules)
	return u
}

// ClearRules clears the value of the "rules" field.
func (u *TLSFingerprintRouterUpsert) ClearRules() *TLSFingerprintRouterUpsert {
	u.SetNull(tlsfingerprintrouter.FieldRules)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TLSFingerprintRouter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TLSFingerprintRouterUpsertOne) UpdateNewValues() *TLSFingerprintRouterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(tlsfingerprintrouter.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TLSFingerprintRouter.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TLSFingerprintRouterUpsertOne) Ignore() *TLSFingerprintRouterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TLSFingerprintRouterUpsertOne) DoNothing() *TLSFingerprintRouterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TLSFingerprintRouterCreate.OnConflict
// documentation for more info.
func (u *TLSFingerprintRouterUpsertOne) Update(set func(*TLSFingerprintRouterUpsert)) *TLSFingerprintRouterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TLSFingerprintRouterUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TLSFingerprintRouterUpsertOne) SetUpdatedAt(v time.Time) *TLSFingerprintRouterUpsertOne {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TLSFingerprintRouterUpsertOne) UpdateUpdatedAt() *TLSFingerprintRouterUpsertOne {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *TLSFingerprintRouterUpsertOne) SetName(v string) *TLSFingerprintRouterUpsertOne {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TLSFingerprintRouterUpsertOne) UpdateName() *TLSFingerprintRouterUpsertOne {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *TLSFingerprintRouterUpsertOne) SetDescription(v string) *TLSFingerprintRouterUpsertOne {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TLSFingerprintRouterUpsertOne) UpdateDescription() *TLSFingerprintRouterUpsertOne {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TLSFingerprintRouterUpsertOne) ClearDescription() *TLSFingerprintRouterUpsertOne {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.ClearDescription()
	})
}

// SetEnabled sets the "enabled" field.
func (u *TLSFingerprintRouterUpsertOne) SetEnabled(v bool) *TLSFingerprintRouterUpsertOne {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *TLSFingerprintRouterUpsertOne) UpdateEnabled() *TLSFingerprintRouterUpsertOne {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.UpdateEnabled()
	})
}

// SetRules sets the "rules" field.
func (u *TLSFingerprintRouterUpsertOne) SetRules(v []model.TLSFingerprintRouterRule) *TLSFingerprintRouterUpsertOne {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.SetRules(v)
	})
}

// UpdateRules sets the "rules" field to the value that was provided on create.
func (u *TLSFingerprintRouterUpsertOne) UpdateRules() *TLSFingerprintRouterUpsertOne {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.UpdateRules()
	})
}

// ClearRules clears the value of the "rules" field.
func (u *TLSFingerprintRouterUpsertOne) ClearRules() *TLSFingerprintRouterUpsertOne {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.ClearRules()
	})
}

// Exec executes the query.
func (u *TLSFingerprintRouterUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TLSFingerprintRouterCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TLSFingerprintRouterUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TLSFingerprintRouterUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TLSFingerprintRouterUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TLSFingerprintRouterCreateBulk is the builder for creating many TLSFingerprintRouter entities in bulk.
type TLSFingerprintRouterCreateBulk struct {
	config
	err      error
	builders []*TLSFingerprintRouterCreate
	conflict []sql.ConflictOption
}

// Save creates the TLSFingerprintRouter entities in the database.
func (_c *TLSFingerprintRouterCreateBulk) Save(ctx context.Context) ([]*TLSFingerprintRouter, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TLSFingerprintRouter, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TLSFingerprintRouterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TLSFingerprintRouterCreateBulk) SaveX(ctx context.Context) []*TLSFingerprintRouter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TLSFingerprintRouterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TLSFingerprintRouterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TLSFingerprintRouter.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TLSFingerprintRouterUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TLSFingerprintRouterCreateBulk) OnConflict(opts ...sql.ConflictOption) *TLSFingerprintRouterUpsertBulk {
	_c.conflict = opts
	return &TLSFingerprintRouterUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TLSFingerprintRouter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TLSFingerprintRouterCreateBulk) OnConflictColumns(columns ...string) *TLSFingerprintRouterUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TLSFingerprintRouterUpsertBulk{
		create: _c,
	}
}

// TLSFingerprintRouterUpsertBulk is the builder for "upsert"-ing
// a bulk of TLSFingerprintRouter nodes.
type TLSFingerprintRouterUpsertBulk struct {
	create *TLSFingerprintRouterCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TLSFingerprintRouter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TLSFingerprintRouterUpsertBulk) UpdateNewValues() *TLSFingerprintRouterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(tlsfingerprintrouter.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TLSFingerprintRouter.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TLSFingerprintRouterUpsertBulk) Ignore() *TLSFingerprintRouterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TLSFingerprintRouterUpsertBulk) DoNothing() *TLSFingerprintRouterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TLSFingerprintRouterCreateBulk.OnConflict
// documentation for more info.
func (u *TLSFingerprintRouterUpsertBulk) Update(set func(*TLSFingerprintRouterUpsert)) *TLSFingerprintRouterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TLSFingerprintRouterUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TLSFingerprintRouterUpsertBulk) SetUpdatedAt(v time.Time) *TLSFingerprintRouterUpsertBulk {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TLSFingerprintRouterUpsertBulk) UpdateUpdatedAt() *TLSFingerprintRouterUpsertBulk {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *TLSFingerprintRouterUpsertBulk) SetName(v string) *TLSFingerprintRouterUpsertBulk {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TLSFingerprintRouterUpsertBulk) UpdateName() *TLSFingerprintRouterUpsertBulk {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *TLSFingerprintRouterUpsertBulk) SetDescription(v string) *TLSFingerprintRouterUpsertBulk {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TLSFingerprintRouterUpsertBulk) UpdateDescription() *TLSFingerprintRouterUpsertBulk {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TLSFingerprintRouterUpsertBulk) ClearDescription() *TLSFingerprintRouterUpsertBulk {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.ClearDescription()
	})
}

// SetEnabled sets the "enabled" field.
func (u *TLSFingerprintRouterUpsertBulk) SetEnabled(v bool) *TLSFingerprintRouterUpsertBulk {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *TLSFingerprintRouterUpsertBulk) UpdateEnabled() *TLSFingerprintRouterUpsertBulk {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.UpdateEnabled()
	})
}

// SetRules sets the "rules" field.
func (u *TLSFingerprintRouterUpsertBulk) SetRules(v []model.TLSFingerprintRouterRule) *TLSFingerprintRouterUpsertBulk {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.SetRules(v)
	})
}

// UpdateRules sets the "rules" field to the value that was provided on create.
func (u *TLSFingerprintRouterUpsertBulk) UpdateRules() *TLSFingerprintRouterUpsertBulk {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.UpdateRules()
	})
}

// ClearRules clears the value of the "rules" field.
func (u *TLSFingerprintRouterUpsertBulk) ClearRules() *TLSFingerprintRouterUpsertBulk {
	return u.Update(func(s *TLSFingerprintRouterUpsert) {
		s.ClearRules()
	})
}

// Exec executes the query.
func (u *TLSFingerprintRouterUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TLSFingerprintRouterCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TLSFingerprintRouterCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TLSFingerprintRouterUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
