// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/tlsfingerprintrouter"
	"github.com/Wei-Shaw/sub2api/internal/model"
)

// TLSFingerprintRouterUpdate is the builder for updating TLSFingerprintRouter entities.
type TLSFingerprintRouterUpdate struct {
	config
	hooks    []Hook
	mutation *TLSFingerprintRouterMutation
}

// Where appends a list predicates to the TLSFingerprintRouterUpdate builder.
func (_u *TLSFingerprintRouterUpdate) Where(ps ...predicate.TLSFingerprintRouter) *TLSFingerprintRouterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TLSFingerprintRouterUpdate) SetUpdatedAt(v time.Time) *TLSFingerprintRouterUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *TLSFingerprintRouterUpdate) SetName(v string) *TLSFingerprintRouterUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TLSFingerprintRouterUpdate) SetNillableName(v *string) *TLSFingerprintRouterUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TLSFingerprintRouterUpdate) SetDescription(v string) *TLSFingerprintRouterUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TLSFingerprintRouterUpdate) SetNillableDescription(v *string) *TLSFingerprintRouterUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TLSFingerprintRouterUpdate) ClearDescription() *TLSFingerprintRouterUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TLSFingerprintRouterUpdate) SetEnabled(v bool) *TLSFingerprintRouterUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TLSFingerprintRouterUpdate) SetNillableEnabled(v *bool) *TLSFingerprintRouterUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetRules sets the "rules" field.
func (_u *TLSFingerprintRouterUpdate) SetRules(v []model.TLSFingerprintRouterRule) *TLSFingerprintRouterUpdate {
	_u.mutation.SetRules(v)
	return _u
}

// AppendRules appends value to the "rules" field.
func (_u *TLSFingerprintRouterUpdate) AppendRules(v []model.TLSFingerprintRouterRule) *TLSFingerprintRouterUpdate {
	_u.mutation.AppendRules(v)
	return _u
}

// ClearRules clears the value of the "rules" field.
func (_u *TLSFingerprintRouterUpdate) ClearRules() *TLSFingerprintRouterUpdate {
	_u.mutation.ClearRules()
	return _u
}

// Mutation returns the TLSFingerprintRouterMutation object of the builder.
func (_u *TLSFingerprintRouterUpdate) Mutation() *TLSFingerprintRouterMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TLSFingerprintRouterUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TLSFingerprintRouterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TLSFingerprintRouterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TLSFingerprintRouterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TLSFingerprintRouterUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tlsfingerprintrouter.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TLSFingerprintRouterUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tlsfingerprintrouter.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintRouter.name": %w`, err)}
		}
	}
	return nil
}

func (_u *TLSFingerprintRouterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tlsfingerprintrouter.Table, tlsfingerprintrouter.Columns, sqlgraph.NewFieldSpec(tlsfingerprintrouter.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(tlsfingerprintrouter.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Rules(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldRules, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRules(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tlsfingerprintrouter.FieldRules, value)
		})
	}
	if _u.mutation.RulesCleared() {
		_spec.ClearField(tlsfingerprintrouter.FieldRules, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tlsfingerprintrouter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TLSFingerprintRouterUpdateOne is the builder for updating a single TLSFingerprintRouter entity.
type TLSFingerprintRouterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TLSFingerprintRouterMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TLSFingerprintRouterUpdateOne) SetUpdatedAt(v time.Time) *TLSFingerprintRouterUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *TLSFingerprintRouterUpdateOne) SetName(v string) *TLSFingerprintRouterUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TLSFingerprintRouterUpdateOne) SetNillableName(v *string) *TLSFingerprintRouterUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TLSFingerprintRouterUpdateOne) SetDescription(v string) *TLSFingerprintRouterUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TLSFingerprintRouterUpdateOne) SetNillableDescription(v *string) *TLSFingerprintRouterUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TLSFingerprintRouterUpdateOne) ClearDescription() *TLSFingerprintRouterUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TLSFingerprintRouterUpdateOne) SetEnabled(v bool) *TLSFingerprintRouterUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TLSFingerprintRouterUpdateOne) SetNillableEnabled(v *bool) *TLSFingerprintRouterUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetRules sets the "rules" field.
func (_u *TLSFingerprintRouterUpdateOne) SetRules(v []model.TLSFingerprintRouterRule) *TLSFingerprintRouterUpdateOne {
	_u.mutation.SetRules(v)
	return _u
}

// AppendRules appends value to the "rules" field.
func (_u *TLSFingerprintRouterUpdateOne) AppendRules(v []model.TLSFingerprintRouterRule) *TLSFingerprintRouterUpdateOne {
	_u.mutation.AppendRules(v)
	return _u
}

// ClearRules clears the value of the "rules" field.
func (_u *TLSFingerprintRouterUpdateOne) ClearRules() *TLSFingerprintRouterUpdateOne {
	_u.mutation.ClearRules()
	return _u
}

// Mutation returns the TLSFingerprintRouterMutation object of the builder.
func (_u *TLSFingerprintRouterUpdateOne) Mutation() *TLSFingerprintRouterMutation {
	return _u.mutation
}

// Where appends a list predicates to the TLSFingerprintRouterUpdate builder.
func (_u *TLSFingerprintRouterUpdateOne) Where(ps ...predicate.TLSFingerprintRouter) *TLSFingerprintRouterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TLSFingerprintRouterUpdateOne) Select(field string, fields ...string) *TLSFingerprintRouterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TLSFingerprintRouter entity.
func (_u *TLSFingerprintRouterUpdateOne) Save(ctx context.Context) (*TLSFingerprintRouter, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TLSFingerprintRouterUpdateOne) SaveX(ctx context.Context) *TLSFingerprintRouter {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TLSFingerprintRouterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TLSFingerprintRouterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TLSFingerprintRouterUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tlsfingerprintrouter.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TLSFingerprintRouterUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tlsfingerprintrouter.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintRouter.name": %w`, err)}
		}
	}
	return nil
}

func (_u *TLSFingerprintRouterUpdateOne) sqlSave(ctx context.Context) (_node *TLSFingerprintRouter, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tlsfingerprintrouter.Table, tlsfingerprintrouter.Columns, sqlgraph.NewFieldSpec(tlsfingerprintrouter.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TLSFingerprintRouter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tlsfingerprintrouter.FieldID)
		for _, f := range fields {
			if !tlsfingerprintrouter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tlsfingerprintrouter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(tlsfingerprintrouter.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Rules(); ok {
		_spec.SetField(tlsfingerprintrouter.FieldRules, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRules(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tlsfingerprintrouter.FieldRules, value)
		})
	}
	if _u.mutation.RulesCleared() {
		_spec.ClearField(tlsfingerprintrouter.FieldRules, field.TypeJSON)
	}
	_node = &TLSFingerprintRouter{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tlsfingerprintrouter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
